/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._main;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _login__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

//\uae30\ubcf8\uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
String userSessionId = "";

String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");

SessionDao mSession = new SessionDao(request, response);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);


// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
//auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
//    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/sysop/main/login.jsp") == -1
            && request.getRequestURI().indexOf("/sysop/user/password_find.jsp") == -1 ) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}




      


//\uac1d\uccb4
UserDao user= new UserDao();
//user.setDebug(out);

//\ud3fc\uccb4\ud06c
f.addElement("login_id", null, "hname:'\ub85c\uadf8\uc778\uc544\uc774\ub514', required:'Y'");
f.addElement("password", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y'");


if (m.isPost()) {

    Calendar startCalendar = new GregorianCalendar();
    Date time = startCalendar.getTime();
    String nowTime = Integer.toString(time.getYear())+Integer.toString(time.getHours())+Integer.toString(time.getMinutes())+ Integer.toString(time.getSeconds());
    String limitTime = "0"; //5\ubd84 \uc2dc\uac04 \uc81c\ud55c

    if(Integer.parseInt(nowTime) < Integer.parseInt(limitTime)){ //\uc2dc\uac04\uc774 \uc544\uc9c1 \uc548 \uc9c0\ub0a8
        m.jsAlert("\ube44\ubc00\ubc88\ud638 5\ud68c \uc624\uc785\ub825\ud588\uc2b5\ub2c8\ub2e4. 5\ubd84 \ub3d9\uc548 \ub85c\uadf8\uc778\uc774 \uc81c\ud55c\ub429\ub2c8\ub2e4.");
        return;
    }

    String password = f.get("password");
    password = m.encrypt(password, "SHA-256");

    loginId = f.get("login_id");

    DataSet info = user.find("login_id = ? AND user_kind = 'A' AND status = 1", new Object[] { loginId });

    if(!info.next()) {
        m.jsAlert("\uc544\uc774\ub514 \ub610\ub294 \ube44\ubc00\ubc88\ud638\uac00 \uc77c\uce58\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
    }

    //\ube44\ubc00\ubc88\ud638 5\ud68c \uc785\ub825\uc778\uc9c0 \ud655\uc778
    if(5 <= info.i("fail_count")){
        limitTime = Integer.toString(time.getYear())+Integer.toString(time.getHours())+Integer.toString(time.getMinutes() + 5)+ Integer.toString(time.getSeconds());
        m.jsAlert("\ube44\ubc00\ubc88\ud638 5\ud68c \uc624\uc785\ub825\ud588\uc2b5\ub2c8\ub2e4. 5\ubd84 \ub3d9\uc548 \ub85c\uadf8\uc778\uc774 \uc81c\ud55c\ub429\ub2c8\ub2e4.");
        return;
    }

    //\uc544\uc774\ub514 \ud655\uc778
    if(!f.get("login_id").equals(info.s("login_id"))) {
        m.jsAlert("\uc544\uc774\ub514 \ub610\ub294 \ube44\ubc00\ubc88\ud638\uac00 \uc77c\uce58\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.2");
        return;
    }

    //\ube44\ubc00\ubc88\ud638 \ud655\uc778
    if (!password.equals(info.s("password"))){
        m.jsAlert("\uc544\uc774\ub514 \ub610\ub294 \ube44\ubc00\ubc88\ud638\uac00 \uc77c\uce58\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.3");
        user.item("fail_count", info.i("fail_count") + 1);
        user.update("id = " + info.i("id"));
        return;
    }

    user.item("fail_count", 0);
    user.update("id = " + info.i("id"));

    //\uc778\uc99d
    auth.put("ID", info.i("id"));
    auth.put("LOGINID", info.s("login_id"));
    auth.put("NAME", info.s("user_nm"));
    auth.put("TYPE", info.s("user_type"));
    auth.save();

    //\uc774\ub3d9
    m.jsAlert("\ub85c\uadf8\uc778 \uc644\ub8cc");
    m.jsReplace("index.jsp", "parent");
    return;
}

p.setLayout("blank");
p.setBody("main.login");
p.setVar("form_script", f.getScript());

p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/main/login.jsp"), 224645755165178121L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -5300827354373470630L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
