/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._algorithm;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.ArrayList;
import java.sql.Array;
import java.util.Collection;
import java.util.Collections;
import java.util.Arrays;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _array_09__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

// \uae30\ubcf8 \uad00\ub9ac\uc790 \uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userType = "";

// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/main/login.jsp") == -1) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}

p.setVar("SYS_TITLE", "[\uad00\ub9ac\uc790] enter \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd \uc0ac\uc774\ud2b8");


      

    String ch = "sysop";

      

    String output ="";
    String output2 ="";

    if(m.isPost()){

        //\uc785\ub825\ubc1b\uc740 \ubb38\uc790\uc5f4
        String inputArray1 = f.get("array1");
            m.p();
            m.p();
            m.p();
        m.p();
        m.p();
        m.p();
        //\uc778\ud2b8\ub85c \ubcc0\ud658
        int num = Integer.parseInt(inputArray1);

        //\uc785\ub825\ubc1b\uc740 \uc22b\uc790\ub9cc\ud07c\uc758 \uc774\ucc28\uc6d0 \ubc30\uc5f4 \uc0dd\uc131
        int [][] array;
        String [] arrayP;

        arrayP = new String[num];

        array = new int[num][num];
        for(int i =0; i <num; i++){
            for(int j=0; j < num; j++){//\uc0dd\uc131\ud558\uba74\uc11c \ucd08\uae30\uac12\uc740 \ub79c\ub364\uac12\uc73c\ub85c \ub123\uc5b4\uc90c. \uc774 \uc22b\uc790\ub294 100\uc774\ud558
                array[i][j] = (int)(Math.random() * 10)+1;
                arrayP[j] = array[i][j] + " ";

            }
//            m.jsAlert(Arrays.toString(arrayP));

            m.p(m.join(",", arrayP));
        }


        ArrayList<Integer> outputArr = new ArrayList();

//        String [] arraySum;
//        arraySum = new String[outputArr.size()];
        //\uc774\uc911 \ub8e8\ud504\ub97c \ub3cc\uba74\uc11c \uac01 \uc5f4\uc758 \ud569 \uad6c\ud558\uae30, \uac01 \ud589\uc758 \ud569 \uad6c\ud558\uae30, \ub300\uac01\uc120 \ub450\uac1c\uc758 \ud569 \uad6c\ud558\uae30.
        // \uad6c\ud55c \uac12\uc740 \ubc30\uc5f4\uc5d0 \ub123\uae30

        int [] arrR = new int[num];
        int [] arrC = new int[num];
        int x1 =0;
        int x2 =0;
        int max = 0;
        for(int i = 0; i < num; i++){
            int sumRow = 0, sumCol = 0;
            for(int j = 0; j < num; j++){
                sumRow += array[i][j];
                sumCol += array[j][i];
                if(i == j ){
                    x1 += array[i][j];
                }
                if(i+j == (num-1)){
                    x2 += array[i][j];
                }
            }
            if(sumRow > max) max = sumRow;
            if(sumCol > max) max = sumCol;
        }
        if(x1 > max) max = x1;
        if(x2 > max) max = x2;
        m.p(max);
//        m.p(Arrays.toString(arrR) );
//        m.p(Arrays.toString(arrC) );
//
//        m.p(x1);
//        m.p(x2);

        //\ucd9c\ub825\ud560 ArrayList \ub97c String \uc73c\ub85c \ubcc0\ud658
//        for(int i = 0 ; i < outputArr.size(); i++){
//            output2 += outputArr.get(i) +" " ;
//        }


        // \uc774 \ubc30\uc5f4\uc5d0\uc11c \uac00\uc7a5 \ud070 \uac12 \ucd9c\ub825
//        int max = Collections.max(outputArr);
//        output = Integer.toString(max);
    }

    p.setLayout(ch);
    p.setBody("algorithm.array_9");
//    p.setVar("output", output);
//    p.setVar("output2", output2);
    p.display();

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/algorithm/array_9.jsp"), 3367870690918121357L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/algorithm/init.jsp"), 8504853130663271725L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -2253010914700824916L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
