/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._algorithm;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _hashmap_01__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

// \uae30\ubcf8 \uad00\ub9ac\uc790 \uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userType = "";

// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/main/login.jsp") == -1) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}

p.setVar("SYS_TITLE", "[\uad00\ub9ac\uc790] enter \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd \uc0ac\uc774\ud2b8");


      

    String ch = "sysop";

      

    String output ="";
    String output1 ="";
    String output2 = "";
    String output3 = "";
    char answer = ' ';
    char answer2 = ' ';


    if(m.isPost()){

        //\uc785\ub825\ubc1b\uc740 \uc2a4\ud2b8\ub9c1
        String str1 = f.get("str1");

        //\ud559\uc0dd\uc218\ub9cc\ud07c \ub4f1\ub85d\ud55c \ud6c4\ubcf4(A,B,C,D,E) \ub97c \uc77c\ub82c\ub9cc\ub4e6.
        //String.toCharArray() : \ubb38\uc790\uc5f4\uc744 \ud558\ub098\uc529 \ucabc\uac1c\uc11c char \ud0c0\uc785\uc758 \ubc30\uc5f4\uc5d0 \ub123\uc5b4\uc90c
        HashMap<Character, Integer> map = new HashMap();
        for(char x : str1.toCharArray()){
            // getOrDefault(Object key, V DefaultValue) : \ucc3e\ub294 \ud0a4\uac00 \uc874\uc7ac\ud558\uba74 \ud0a4 \uac12 \ubc18\ud658, \uc5c6\uc73c\uba74 \uae30\ubcf8\uac12 \ubc18\ud658
            map.put(x, map.getOrDefault(x, 0) +1);
        }

        int max = Integer.MIN_VALUE; // \uc815\uc218\uc758 \ucd5c\uc18c\uac12

        for(char key : map.keySet()){ //\uc800\uc7a5\ub41c \ud0a4 \uac12 \ud655\uc778
            if(map.get(key) > max){ //\ud0a4\uc758 \ubc38\ub958 \uac12\uacfc max\uac12 \ube44\uad50
                max = map.get(key);
                answer = key;
            }
        }
        output = Character.toString(answer);

        char a= ' ';
        int b = 0;
        ArrayList<String> arr = new ArrayList();
        for(Map.Entry<Character, Integer> entrySet : map.entrySet()){
            a = entrySet.getKey();
            b = entrySet.getValue();
            output1= Character.toString(a);
            arr.add(output1 + " : ");
            output2= Integer.toString(b);
            arr.add(output2 + " , ");
        }

        for (int i = 0; i < arr.size(); i++) {
            output3 += arr.get(i);
        }

        //String st = new String(charArr);  : char\ud615 \ubc30\uc5f4 \ud569\uccd0\uc11c \ud558\ub098\uc758 String \ub9cc\ub4e4\uae30
        //entrySet()  \ud0a4, \ubc38\ub958 \uac12 \uac00\uc838\uc634
        //keySey()  \ud0a4 \uac12 \uac00\uc838\uc634
    }

    p.setLayout(ch);
    p.setBody("algorithm.hashmap_1");
    p.setVar("output", output);
    p.setVar("output1", output1);
    p.setVar("output2", output2);
    p.setVar("output2", output3);
    p.display();

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/algorithm/hashmap_1.jsp"), -3631256084175890078L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/algorithm/init.jsp"), 8504853130663271725L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -2253010914700824916L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n\r\n".toCharArray();
  }
}
