/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._user;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _user_0insert__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

//\uae30\ubcf8\uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
String userSessionId = "";

String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");

SessionDao mSession = new SessionDao(request, response);


Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);

auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "KAYAKEY";

/*if(auth.isValid()) {

    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGIN_ID");
    userName = auth.getString("USERNAME");
//    email = auth.getString("EMAIL");
    userKind = auth.getString("KIND");

    userSessionId = auth.getString("SESSIONID");
}*/




      

String ch = "user";


      


//\uac1d\uccb4
UserDao user = new UserDao();

//\ud3fc\uccb4\ud06c
f.addElement("login_id", null, "hname:'\ud68c\uc6d0\uc544\uc774\ub514', required:'Y'");
//f.addElement("user_nm", null, "hname:'\ud68c\uc6d0\uba85', required:'Y'");
f.addElement("password", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y'");
f.addElement("password2", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y'");
f.addElement("email", null, "hname:'\uc774\uba54\uc77c'");
f.addElement("phone", null, "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638'");


f.addElement("zipcode", null, "hname:'\uc6b0\ud3b8\ubc88\ud638'");
f.addElement("address", null, "hname:'\uc8fc\uc18c'");
f.addElement("address_detail", null, "hname:'\uc0c1\uc138\uc8fc\uc18c'");

f.addElement("birthday", null, "hname:'\uc0dd\ub144\uc6d4\uc77c'");
//f.addElement("status", 1, "hname:'\uc0c1\ud0dc', required:'Y'");

//\uc81c\ud55c

//\ub4f1\ub85d
if (m.isPost() && f.validate()) {
    //\ub85c\uadf8\uc778 \uc544\uc774\ub514 \uc911\ubcf5\uccb4\ud06c
    String login_id = f.get("login_id");
    int checkLoginId = user.findCount("login_id = '" + f.get("login_id") + "'");
    m.jsAlert(checkLoginId+"");
    if (0 < checkLoginId) {
        m.jsAlert("\uc774\ubbf8 \uc0ac\uc6a9 \uc911\uc778 \uc544\uc774\ub514\uc785\ub2c8\ub2e4.");
        return;
    }
    //\ube44\ubc00\ubc88\ud638 8\uc790 \uc774\uc0c1 \uc601\ubb38,\uc22b\uc790,\ub300\ubb38\uc790,\ud2b9\uc218\uae30\ud638 \ud3ec\ud568
    String pwPattern = "^(?=.*[a-zA-Z])(?=.*\\d)(?=.*\\W).{8,20}$";
    if (!f.get("password").matches(pwPattern)){
        m.jsAlert("\ube44\ubc00\ubc88\ud638\ub294 8\uc790 \uc774\uc0c1 \uc601\ubb38, \uc22b\uc790, \ub300\ubb38\uc790, \ud2b9\uc218\uae30\ud638\ub97c \ud3ec\ud568\ud574\uc57c\ud569\ub2c8\ub2e4.");
        return;
    }
    //\uc774\uba54\uc77c \uc911\ubcf5\uccb4\ud06c
    String email = f.get("email");
    int checkEmail = user.findCount("email= '" + email + "'");
    if (0 < checkEmail) {
        m.jsAlert("\uc774\ubbf8 \uc0ac\uc6a9 \uc911\uc778 \uc774\uba54\uc77c\uc785\ub2c8\ub2e4.");
//        return;
    }
    //\ube44\ubc00\ubc88\ud638 \uc554\ud638\ud654 SHA256
    String password = f.get("password");
    password = m.encrypt(password, "SHA-256");

    //\ud734\ub300\uc804\ud654\ubc88\ud638 \ud615\uc2dd\uccb4\ud06c
    String phone = f.get("phone");
    String phonePattern = "^01(?:0|1|[6-9])-(?:\\d{3}|\\d{4})-\\d{4}$";
    if (!f.get("phone").matches(phonePattern)) {
        m.jsAlert("\uc62c\ubc14\ub978 \ud734\ub300\uc804\ud654\ubc88\ud638\uac00 \uc544\ub2d9\ub2c8\ub2e4.");
    }

    //\ud734\ub300\uc804\ud654\ubc88\ud638 \uc554\ud638\ud654 AES128
    String [] phoneArr = phone.split("-");
    phone = m.join("", phoneArr);
    user.item("phone", SimpleAES.encrypt(phone));

    //\ud68c\uc6d0\uc774\ubbf8\uc9c0

    //\uc0ac\uc9c4\ud30c\uc77c \ucca8\ubd80 \uc5ec\ub7ec\uac1c - pdf, \uc774\ubbf8\uc9c0

    //\uad00\uc2ec\ubd84\uc57c


    user.item("login_id", login_id);
    user.item("password", password);
    user.item("email", email);

//    user.item();
    user.item("reg_date", sysNow);
    user.item("status", f.getInt("status"));

    int newId = user.insert(true);
    if(newId == 0) { m.jsAlert("\ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

    m.jsAlert("\ub4f1\ub85d\ud588\uc2b5\ub2c8\ub2e4.");


}

p.setLayout("sysop");
p.setBody("user.user_insert");
p.setVar("form_script", f.getScript());



p.display();



    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/user_insert.jsp"), 3906591976087404259L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/init.jsp"), 1782085437888379153L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -4446093587189101146L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
